alias cdproj="cd ~/Work/Projects/"
alias cdappl="cd ~/Work/Projects/Applifier/"
alias reloadshell="source ~/.zshrc"
alias startmongo="mongod run --config /usr/local/etc/mongod.conf"
alias startredis="redis-server /usr/local/etc/redis.conf"
alias startpg="postgres -D /usr/local/var/postgres -p 5432"
alias startes="elasticsearch -f -D es.config=/usr/local/opt/elasticsearch/config/elasticsearch.yml"